name: test
version: 1.22.1
description: >-
  A full featured library for writing and running Dart tests across platforms.
repository: https://github.com/dart-lang/test/tree/master/pkgs/test

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  analyzer: '>=2.0.0 <6.0.0'
  async: ^2.5.0
  boolean_selector: ^2.1.0
  collection: ^1.15.0
  coverage: ^1.0.1
  http_multi_server: ^3.0.0
  io: ^1.0.0
  js: ^0.6.4
  node_preamble: ^2.0.0
  package_config: ^2.0.0
  path: ^1.8.0
  pool: ^1.5.0
  shelf: ^1.0.0
  shelf_packages_handler: ^3.0.0
  shelf_static: ^1.0.0
  shelf_web_socket: ^1.0.0
  source_span: ^1.8.0
  stack_trace: ^1.10.0
  stream_channel: ^2.1.0
  typed_data: ^1.3.0
  web_socket_channel: ^2.0.0
  webkit_inspection_protocol: ^1.0.0
  yaml: ^3.0.0
  # Use an exact version until the test_api and test_core package are stable.
  test_api: 0.4.17
  test_core: 0.4.21

dev_dependencies:
  fake_async: ^1.0.0
  glob: ^2.0.0
  lints: '>=1.0.0 <3.0.0'
  test_descriptor: ^2.0.0
  test_process: ^2.0.0

dependency_overrides:
  test_core:
    path: ../test_core
  test_api:
    path: ../test_api
