name: matcher
version: 0.12.14
description: >-
  Support for specifying test expectations via an extensible Matcher class.
  Also includes a number of built-in Matcher implementations for common cases.
repository: https://github.com/dart-lang/matcher

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  meta: ^1.8.0
  stack_trace: ^1.10.0

dev_dependencies:
  lints: ^2.0.0
  test: any
  test_api: any
  test_core: any

dependency_overrides:
  test_api: any
