---
name: python3-configobj
buildsystem: simple
build-commands:
  - python3 setup.py install --prefix=/app --root=/
sources:
  - type: archive
    url: https://files.pythonhosted.org/packages/64/61/079eb60459c44929e684fa7d9e2fdca403f67d64dd9dbac27296be2e0fab/configobj-5.0.6.tar.gz
    sha256: a2f5650770e1c87fb335af19a9b7eb73fc05ccf22144eb68db7d00cd2bcb0902
