stages:
  - validation
  - build

json:
  image: python:3.6
  stage: validation
  allow_failure: false
  script:
    - python -m json.tool org.fdroid.Repomaker.json

flatpak:
  image: flatpak/flatpak-builder:base
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  allow_failure: true
  when: manual
  cache:
    paths:
      - .flatpak-builder/cache
  artifacts:
    paths:
    - repomaker-flatpak/
    expire_in: 1 week
  script:
    - flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak-builder builddir --install-deps-from=flathub --user --repo=repomaker-flatpak --force-clean org.fdroid.Repomaker.json
