app-id: io.github.taylan.grubsettings
runtime: org.gnome.Platform
runtime-version: '46'
sdk: org.gnome.Sdk
command: grub-settings
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --filesystem=host
  - --talk-name=org.freedesktop.Flatpak

modules:
  - name: grub-settings
    buildsystem: simple
    build-commands:
      # Install main app as executable
      - install -D grub_settings.py /app/bin/grub-settings
      - chmod +x /app/bin/grub-settings
      
      # Add shebang for source execution
      - sed -i '1i#!/usr/bin/env python3' /app/bin/grub-settings
      
      # Copy assets folder
      - mkdir -p /app/share/grub-settings
      - cp -r assets /app/share/grub-settings/assets
      
      # Copy locales folder (i18n)
      - cp -r locales /app/share/grub-settings/locales
      
      # Install desktop and metainfo files
      - install -D flatpak/io.github.taylan.grubsettings.desktop /app/share/applications/io.github.taylan.grubsettings.desktop
      - install -D flatpak/io.github.taylan.grubsettings.metainfo.xml /app/share/metainfo/io.github.taylan.grubsettings.metainfo.xml
      
      # Install icon (256x256 required by Flathub)
      - install -D assets/icon.png /app/share/icons/hicolor/256x256/apps/io.github.taylan.grubsettings.png
      
    sources:
      - type: git
        url: https://github.com/bingoweb/grub-settings.git
        commit: 89a2ead797da18312cd1385695dde1933a55b97d

