app-id: io.github.taylan.grubsettings
runtime: org.gnome.Platform
runtime-version: '46'
sdk: org.gnome.Sdk
command: grub-settings
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --filesystem=host
  - --talk-name=org.freedesktop.Flatpak

modules:
  - name: grub-settings
    buildsystem: simple
    build-commands:
      # Ana uygulama dosyasını çalıştırılabilir olarak kopyala
      - install -D grub_settings.py /app/bin/grub-settings
      - chmod +x /app/bin/grub-settings
      
      # Shebang ekle (PyInstaller olmadığı için source çalışacak)
      - sed -i '1i#!/usr/bin/env python3' /app/bin/grub-settings
      
      # Assets klasörünü kopyala
      - mkdir -p /app/share/grub-settings
      - cp -r assets /app/share/grub-settings/assets
      
      # Desktop ve Metadata dosyalarını kopyala
      - install -D flatpak/io.github.taylan.grubsettings.desktop /app/share/applications/io.github.taylan.grubsettings.desktop
      - install -D flatpak/io.github.taylan.grubsettings.metainfo.xml /app/share/metainfo/io.github.taylan.grubsettings.metainfo.xml
      
      # İkonu kopyala
      - install -D assets/icon.png /app/share/icons/hicolor/128x128/apps/io.github.taylan.grubsettings.png
      
    sources:
      - type: git
        url: https://github.com/bingoweb/grub-settings.git
        commit: 42873d6bef78ce45d8123284aa17865727918548
