name: Run flatpak-node-generator tests

on:
  push:
    paths:
      - node/**
  pull_request:
    paths:
      - node/**

defaults:
  run:
    working-directory: node

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
        poetry-version:
          - '1.6.1'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install OS dependencies
        run: sudo apt-get update && sudo apt-get install -y flatpak-builder
      - name: Install Flatpak dependencies
        run: |
          flatpak --user remote-add flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak --user install -y flathub \
            org.freedesktop.{Platform,Sdk{,.Extension.node{14,16,18}}}//22.08
      - name: Install dependencies
        run: poetry install
      - name: Run checks
        run: poetry run poe check
