[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/jackpot51/rust-atomicwrites"]
git = "https://github.com/jackpot51/rust-atomicwrites"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/cosmic-protocols?rev=d0e95be"]
git = "https://github.com/pop-os/cosmic-protocols"
rev = "d0e95be"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/cosmic-text.git"]
git = "https://github.com/pop-os/cosmic-text.git"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/dbus-settings-bindings"]
git = "https://github.com/pop-os/dbus-settings-bindings"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/freedesktop-icons"]
git = "https://github.com/pop-os/freedesktop-icons"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/glyphon.git?tag=iced-0.14-dev"]
git = "https://github.com/pop-os/glyphon.git"
tag = "iced-0.14-dev"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/libcosmic.git?rev=aabc8dcda530a6ac70617dd578cea55910af53c8"]
git = "https://github.com/pop-os/libcosmic.git"
rev = "aabc8dcda530a6ac70617dd578cea55910af53c8"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/smithay-clipboard?tag=pop-dnd-5"]
git = "https://github.com/pop-os/smithay-clipboard"
tag = "pop-dnd-5"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/softbuffer?tag=cosmic-4.0"]
git = "https://github.com/pop-os/softbuffer"
tag = "cosmic-4.0"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/window_clipboard.git?tag=pop-0.13-2"]
git = "https://github.com/pop-os/window_clipboard.git"
tag = "pop-0.13-2"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/winit.git?tag=iced-xdg-surface-0.13-rc"]
git = "https://github.com/pop-os/winit.git"
tag = "iced-xdg-surface-0.13-rc"
replace-with = "vendored-sources"

[source."git+https://github.com/wash2/accesskit?tag=iced-xdg-surface-0.13-rc"]
git = "https://github.com/wash2/accesskit"
tag = "iced-xdg-surface-0.13-rc"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
