name: Archive EOL repositories

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  archive:
    name: Archive EOL repositories
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y flatpak python3 python3-pip
          pip3 install 'PyGithub==2.3.0'

      - name: Set up Flathub remotes
        run: |
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak remote-add --user --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo

      - name: Run EOL script
        run: python3 .github/scripts/archive_eol.py
        env:
          GITHUB_TOKEN: ${{ secrets.FLATHUBBOT_TOKEN }}

#      - name: Run orphan script
#        run: python3 .github/scripts/archive_orphan.py
