name: Build Flatpak

on:
  push:
    branches:
      - "*"
      - "!master"
  workflow_dispatch:

jobs:
  build-flatpak-bundle:
    name: "Build flatpak bundle"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    strategy:
      matrix:
        arch:
          - x86_64
          # - arm64
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set up Docker
      if: ${{ matrix.arch != 'x86_64' }}
      run: |
        dnf install -y docker

    - name: Set up QEMU
      if: ${{ matrix.arch != 'x86_64' }}
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Get current date
      id: date
      run: echo "DATESTAMP=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: ${{ github.head_ref || github.ref_name }}_${{ steps.date.outputs.date }}_${{ matrix.arch }}.flatpak
        manifest-path: ${{ github.head_ref || github.ref_name }}.yml
        cache-key: flatpak-builder-${{ github.sha }}_${{ matrix.arch }}
        upload-artifact: true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.head_ref || github.ref_name }}_${{ steps.date.outputs.date }}_${{ matrix.arch }}.flatpak
        path: ${{ github.head_ref || github.ref_name }}_${{ steps.date.outputs.date }}_${{ matrix.arch }}.flatpak
        retention-days: 0

  release-bundle:
    name: "Release flatpak bundle"
    runs-on: ubuntu-latest
    needs:
      - build-flatpak-bundle
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4

    - name: Get current date
      id: date
      run: echo "DATESTAMP=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.head_ref || github.ref_name }}
        generate_release_notes: true
        append_body: true
        files: |
          ${{ github.head_ref || github.ref_name }}_${{ env.DATESTAMP }}_x86_64.flatpak
          ${{ github.head_ref || github.ref_name }}_${{ env.DATESTAMP }}_arm64.flatpak
