name: Build Flatpak bundles
on:
  push:
    branches:
      - 'org.mozilla.FirefoxESR'
  workflow_dispatch:
jobs:
  Build-Flatpak-Bundle:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '#buildme') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - id: determine_freedesktop_version
        name: Determine target runtime version
        run: |
          echo "runtime_version=$(jq --raw-output '."runtime-version"' ./BaseApp/org.mozilla.firefox.BaseApp.json)" >> $GITHUB_OUTPUT
      # TODO: Specifying runtime version here is prone to future errors.
      - name: Setup dependencies
        env:
          FREEDESKTOP_RUNTIME_VERSION: ${{steps.determine_freedesktop_version.outputs.runtime_version}}
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y flatpak flatpak-builder
          flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y --user org.freedesktop.Sdk/x86_64/$FREEDESKTOP_RUNTIME_VERSION
          flatpak install -y --user org.freedesktop.Platform/x86_64/$FREEDESKTOP_RUNTIME_VERSION
          flatpak install -y --user org.mozilla.firefox.BaseApp//$FREEDESKTOP_RUNTIME_VERSION
      - name: Build flatpak bundle
        run: |
          mkdir out
          flatpak-builder --repo=repo app ./org.mozilla.firefox_esr.json 
          flatpak build-bundle repo out/main.flatpak org.mozilla.firefox_esr
          flatpak build-bundle repo out/locale.flatpak org.mozilla.firefox_esr.Locale --runtime
      - name: Upload bundles
        uses: actions/upload-artifact@v3
        with: 
          name: Bundles
          path: ./out/*.flatpak
          if-no-files-found: error
