name: Flatpak

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: freedesktopsdk/flatpak:20.08-x86_64
      options: --privileged --tmpfs /tmp -v /var/tmp -v /root/.local/share/flatpak

    steps:
      - uses: actions/checkout@v2

      - name: Prime cache
        uses: actions/cache@v2
        with:
          path: |
            .flatpak-builder/ccache
          key: flatpak-builder-${{ github.run_id }}
          restore-keys: |
            flatpak-builder-

      - name: Build flatpak
        uses: gasinvein/action-flatpak-build@master
        id: build_flatpak
        with:
          kind: app
          id: org.winehq.Wine
          arch: x86_64
          branch: stable

      - name: Publish to OSTree repo
        if: github.ref == 'refs/heads/master'
        uses: vrutkovs/action-flatpak-upload@main
        with:
          build-repo-path: ${{ steps.build_flatpak.outputs.build-repo }}
          url: https://flatpak.russianfedora.online/repo
          name: stable
          token: ${{ secrets.FLATPAK_REPO_TOKEN }}
