name: Flatpak

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: freedesktopsdk/flatpak:20.08-x86_64
      options: --privileged --tmpfs /tmp -v /var/tmp -v /root/.local/share/flatpak

    steps:
      - uses: actions/checkout@v2

      - name: Prime cache
        uses: actions/cache@v2
        with:
          path: |
            .flatpak-builder/ccache
          key: flatpak-builder-${{ github.run_id }}
          restore-keys: |
            flatpak-builder-

      - name: Build flatpak
        uses: gasinvein/action-flatpak-build@master
        id: build_flatpak
        with:
          kind: app
          id: org.winehq.Wine
          arch: x86_64
          branch: master

      - name: Upload flatpak
        uses: actions/upload-artifact@v2
        with:
          name: wine-build-repo
          path: ${{ steps.build_flatpak.outputs.build-repo }}
