name: "Close stale PR"
on:
  schedule:
  - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # 9.1.0
    - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: |-
          This hasn't received any updates in 6 months and will be
          automatically closed in 7 days. Please comment or reopen if
          necessary.
        stale-pr-message: |-
          This hasn't received any updates in 6 months and will be
          automatically closed in 7 days. Please comment or reopen if
          necessary.
        days-before-stale: 183
        days-before-close: 7
        any-of-issue-labels: quality-guidelines
        any-of-pr-labels: awaiting-changes,blocked,work-in-progress,awaiting-upstream
        remove-stale-when-updated: true
        exempt-issue-labels: leave-open
        exempt-pr-labels: leave-open
        operations-per-run: 500
        ascending: true
